// 상식 퀴즈 게임 - 문제 데이터
// 카테고리 4개(한국사, 과학, 일반상식, 의학) x 난이도 4개(하/중/상/최상) x 5문제 = 총 80문제
// 난이도 기준: 하=초등학생, 중=고등학생, 상=대학생, 최상=그 분야를 공부하는 사람
// 각 문제 형태: { id, category, difficulty, question, choices[4], answerIndex, explanation }
const questions = [
  // ===== 한국사 - 하 =====
  {
    id: 1,
    category: "한국사",
    difficulty: "하",
    question: "조선을 세운 인물은 누구일까요?",
    choices: ["왕건", "이성계", "김유신", "세종대왕"],
    answerIndex: 1,
    explanation: "이성계는 1392년 고려를 무너뜨리고 조선을 세웠어요.",
  },
  {
    id: 2,
    category: "한국사",
    difficulty: "하",
    question: "세종대왕이 만든 우리 고유의 문자는 무엇일까요?",
    choices: ["이두", "한자", "훈민정음", "향찰"],
    answerIndex: 2,
    explanation: "훈민정음은 1443년 세종대왕이 창제한 우리나라 고유 문자예요.",
  },
  {
    id: 3,
    category: "한국사",
    difficulty: "하",
    question: "임진왜란 때 이순신 장군이 사용한, 거북 모양의 배는 무엇일까요?",
    choices: ["판옥선", "거북선", "장갑선", "전투선"],
    answerIndex: 1,
    explanation: "거북선은 이순신 장군이 이끌던 조선 수군의 대표적인 군함이에요.",
  },
  {
    id: 4,
    category: "한국사",
    difficulty: "하",
    question: "우리나라가 일제로부터 해방된 광복절은 몇 월 며칠일까요?",
    choices: ["3월 1일", "6월 25일", "8월 15일", "10월 3일"],
    answerIndex: 2,
    explanation: "1945년 8월 15일에 광복을 맞았어요.",
  },
  {
    id: 5,
    category: "한국사",
    difficulty: "하",
    question: "우리나라 삼국시대를 이룬 세 나라는 무엇일까요?",
    choices: ["고구려, 백제, 가야", "고구려, 백제, 신라", "신라, 가야, 발해", "백제, 신라, 발해"],
    answerIndex: 1,
    explanation: "삼국시대는 고구려, 백제, 신라가 경쟁하던 시기예요.",
  },

  // ===== 한국사 - 중 =====
  {
    id: 6,
    category: "한국사",
    difficulty: "중",
    question: "고려 무신정권 시기 최고 권력을 오랫동안 잡았던 가문은 어디일까요?",
    choices: ["최씨(최충헌) 가문", "김씨 가문", "이씨 가문", "왕씨 가문"],
    answerIndex: 0,
    explanation: "최충헌을 시작으로 한 최씨 가문은 4대에 걸쳐 고려의 실권을 장악했어요.",
  },
  {
    id: 7,
    category: "한국사",
    difficulty: "중",
    question: "목민심서를 지은 조선 후기 실학자는 누구일까요?",
    choices: ["박지원", "정약용", "이익", "유형원"],
    answerIndex: 1,
    explanation: "정약용은 목민심서 등을 통해 지방 관리의 자세를 강조한 실학자예요.",
  },
  {
    id: 8,
    category: "한국사",
    difficulty: "중",
    question: "갑오개혁이 일어난 연도는 언제일까요?",
    choices: ["1884년", "1894년", "1904년", "1910년"],
    answerIndex: 1,
    explanation: "갑오개혁은 1894년 조선의 정치·사회 제도를 근대적으로 바꾸려 한 개혁이에요.",
  },
  {
    id: 9,
    category: "한국사",
    difficulty: "중",
    question: "임진왜란 중 선조 때 설치된, 조선의 중앙 군사 조직은 무엇일까요?",
    choices: ["별기군", "훈련도감", "장용영", "의흥친군위"],
    answerIndex: 1,
    explanation: "훈련도감은 1593년 임진왜란 중 선조 때 설치된 군사 조직이에요.",
  },
  {
    id: 10,
    category: "한국사",
    difficulty: "중",
    question: "병자호란이 일어난 연도는 언제일까요?",
    choices: ["1592년", "1627년", "1636년", "1650년"],
    answerIndex: 2,
    explanation: "병자호란은 1636년 청나라가 조선을 침입한 전쟁이에요.",
  },

  // ===== 한국사 - 상 =====
  {
    id: 11,
    category: "한국사",
    difficulty: "상",
    question: "신라 하대 지방 호족 세력과 밀접하게 연결되었던 불교 사상은 무엇일까요?",
    choices: ["교종", "선종", "밀교", "정토종"],
    answerIndex: 1,
    explanation: "선종은 형식보다 개인의 깨달음을 중시해 지방 호족들의 지지를 받았어요.",
  },
  {
    id: 12,
    category: "한국사",
    difficulty: "상",
    question: "조선에서 대동법을 최초로 시행한 지역은 어디일까요?",
    choices: ["경기도", "전라도", "충청도", "경상도"],
    answerIndex: 0,
    explanation: "대동법은 1608년 광해군 때 경기도에서 처음 시행됐어요.",
  },
  {
    id: 13,
    category: "한국사",
    difficulty: "상",
    question: "고려 원 간섭기, 원이 철령 이북 지역에 설치했던 통치 기구는 무엇일까요?",
    choices: ["동녕부", "쌍성총관부", "탐라총관부", "정동행성"],
    answerIndex: 1,
    explanation: "쌍성총관부는 원이 고려의 함경도 일대를 직접 지배하려고 설치한 기구예요.",
  },
  {
    id: 14,
    category: "한국사",
    difficulty: "상",
    question: "동학농민운동 중 전주화약을 이끌어낸 지도자는 누구일까요?",
    choices: ["김옥균", "전봉준", "최제우", "서재필"],
    answerIndex: 1,
    explanation: "전봉준은 동학농민군을 이끌며 정부와 전주화약을 맺었어요.",
  },
  {
    id: 15,
    category: "한국사",
    difficulty: "상",
    question: "을사조약 체결에 저항해 자결한 인물로 유명한 사람은 누구일까요?",
    choices: ["안중근", "민영환", "윤봉길", "이봉창"],
    answerIndex: 1,
    explanation: "민영환은 1905년 을사조약에 반대하며 스스로 목숨을 끊었어요.",
  },

  // ===== 한국사 - 최상 =====
  {
    id: 16,
    category: "한국사",
    difficulty: "최상",
    question: "나당전쟁 중 신라가 당의 대군을 크게 격파한 전투는 무엇일까요?",
    choices: ["황산벌 전투", "매소성 전투", "안시성 전투", "살수 대첩"],
    answerIndex: 1,
    explanation: "매소성 전투(675년)에서 신라는 당군을 크게 격파하며 삼국통일을 앞당겼어요.",
  },
  {
    id: 17,
    category: "한국사",
    difficulty: "최상",
    question: "고려 광종이 실시한, 억울하게 노비가 된 사람을 원래 신분으로 되돌린 정책은 무엇일까요?",
    choices: ["과전법", "노비안검법", "공음전", "전시과"],
    answerIndex: 1,
    explanation: "노비안검법은 호족의 세력 기반이던 노비를 풀어줘 왕권을 강화하려는 정책이었어요.",
  },
  {
    id: 18,
    category: "한국사",
    difficulty: "최상",
    question: "조선 선조 때 정여립 모반 사건으로 일어난, 동인이 큰 화를 입은 사건은 무엇일까요?",
    choices: ["기축옥사", "임오군란", "기묘사화", "을사사화"],
    answerIndex: 0,
    explanation: "기축옥사(1589)는 정여립 모반 사건을 계기로 동인이 대규모로 화를 입은 사건이에요.",
  },
  {
    id: 19,
    category: "한국사",
    difficulty: "최상",
    question: "대한제국이 근대적 토지 소유권 확립을 위해 실시한 토지 조사 사업은 무엇일까요?",
    choices: ["광무양전", "동학양전", "삼정이정", "균역법"],
    answerIndex: 0,
    explanation: "광무양전은 대한제국이 지계를 발급하며 실시한 근대적 토지 조사 사업이에요.",
  },
  {
    id: 20,
    category: "한국사",
    difficulty: "최상",
    question: "신라 6두품 출신으로 시무10조를 건의한 학자는 누구일까요?",
    choices: ["설총", "최치원", "김대문", "강수"],
    answerIndex: 1,
    explanation: "최치원은 6두품 출신으로 신라 말 개혁안인 시무10조를 건의했어요.",
  },

  // ===== 과학 - 하 =====
  {
    id: 21,
    category: "과학",
    difficulty: "하",
    question: "물을 이루는 화학식은 무엇일까요?",
    choices: ["CO2", "O2", "NaCl", "H2O"],
    answerIndex: 3,
    explanation: "물은 수소 2개와 산소 1개가 결합한 H2O예요.",
  },
  {
    id: 22,
    category: "과학",
    difficulty: "하",
    question: "태양계에서 가장 큰 행성은 무엇일까요?",
    choices: ["지구", "화성", "목성", "토성"],
    answerIndex: 2,
    explanation: "목성은 태양계 행성 중 크기가 가장 커요.",
  },
  {
    id: 23,
    category: "과학",
    difficulty: "하",
    question: "식물이 빛을 이용해 스스로 양분을 만드는 과정은 무엇일까요?",
    choices: ["호흡", "발효", "광합성", "증발"],
    answerIndex: 2,
    explanation: "광합성은 빛, 물, 이산화탄소로 포도당과 산소를 만드는 과정이에요.",
  },
  {
    id: 24,
    category: "과학",
    difficulty: "하",
    question: "사람 몸에서 혈액을 온몸으로 순환시키는 기관은 무엇일까요?",
    choices: ["폐", "심장", "간", "위"],
    answerIndex: 1,
    explanation: "심장은 펌프처럼 뛰며 혈액을 온몸으로 보내요.",
  },
  {
    id: 25,
    category: "과학",
    difficulty: "하",
    question: "무지개는 보통 몇 가지 색깔로 표현될까요?",
    choices: ["5가지", "6가지", "7가지", "8가지"],
    answerIndex: 2,
    explanation: "무지개는 흔히 빨주노초파남보 7가지 색으로 표현돼요.",
  },

  // ===== 과학 - 중 =====
  {
    id: 26,
    category: "과학",
    difficulty: "중",
    question: "원자핵을 구성하는 두 입자는 무엇일까요?",
    choices: ["전자와 중성자", "양성자와 중성자", "전자와 양성자", "양성자와 광자"],
    answerIndex: 1,
    explanation: "원자핵은 양성자와 중성자로 이루어져 있고, 전자는 핵 주위를 돌아요.",
  },
  {
    id: 27,
    category: "과학",
    difficulty: "중",
    question: "세포 안에서 에너지(ATP)를 주로 만들어내는 소기관은 무엇일까요?",
    choices: ["리보솜", "미토콘드리아", "엽록체", "골지체"],
    answerIndex: 1,
    explanation: "미토콘드리아는 세포호흡을 통해 에너지를 만드는 '세포의 발전소'예요.",
  },
  {
    id: 28,
    category: "과학",
    difficulty: "중",
    question: "지진의 세기를 나타내는 척도로 널리 쓰이는 것은 무엇일까요?",
    choices: ["리히터 규모", "섭씨 온도", "데시벨", "기압"],
    answerIndex: 0,
    explanation: "리히터 규모는 지진의 크기(에너지)를 나타내는 척도예요.",
  },
  {
    id: 29,
    category: "과학",
    difficulty: "중",
    question: "유전 정보를 저장하는 물질의 이름은 무엇일까요?",
    choices: ["RNA", "단백질", "DNA", "지질"],
    answerIndex: 2,
    explanation: "DNA(디옥시리보핵산)는 생물의 유전 정보를 담고 있는 물질이에요.",
  },
  {
    id: 30,
    category: "과학",
    difficulty: "중",
    question: "뉴턴의 운동 법칙 중 '힘 = 질량 × 가속도'를 나타내는 법칙은 무엇일까요?",
    choices: ["제1법칙(관성)", "제2법칙(가속도)", "제3법칙(작용-반작용)", "만유인력의 법칙"],
    answerIndex: 1,
    explanation: "뉴턴 제2법칙은 힘, 질량, 가속도 사이의 관계(F=ma)를 나타내요.",
  },

  // ===== 과학 - 상 =====
  {
    id: 31,
    category: "과학",
    difficulty: "상",
    question: "원자와 입자의 세계를 다루는, 슈뢰딩거 방정식이 속한 물리학 분야는 무엇일까요?",
    choices: ["고전역학", "열역학", "양자역학", "전자기학"],
    answerIndex: 2,
    explanation: "슈뢰딩거 방정식은 양자역학에서 입자의 상태를 기술하는 핵심 방정식이에요.",
  },
  {
    id: 32,
    category: "과학",
    difficulty: "상",
    question: "DNA가 복제될 때 새로운 가닥을 합성하는 효소는 무엇일까요?",
    choices: ["RNA 중합효소", "DNA 중합효소", "리가아제", "헬리케이스"],
    answerIndex: 1,
    explanation: "DNA 중합효소(polymerase)가 주형을 따라 새로운 DNA 가닥을 합성해요.",
  },
  {
    id: 33,
    category: "과학",
    difficulty: "상",
    question: "열역학 제2법칙과 밀접하게 관련된 물리량은 무엇일까요?",
    choices: ["엔탈피", "엔트로피", "운동량", "전위"],
    answerIndex: 1,
    explanation: "열역학 제2법칙은 고립계의 엔트로피가 항상 증가하는 방향으로 변한다는 법칙이에요.",
  },
  {
    id: 34,
    category: "과학",
    difficulty: "상",
    question: "세포호흡 단계 중 산소를 이용해 가장 많은 ATP를 만드는 단계는 무엇일까요?",
    choices: ["해당작용", "크렙스 회로", "전자전달계", "발효"],
    answerIndex: 2,
    explanation: "전자전달계(산화적 인산화)에서 산소를 이용해 대부분의 ATP가 생성돼요.",
  },
  {
    id: 35,
    category: "과학",
    difficulty: "상",
    question: "아인슈타인이 특수상대성이론을 발표한 연도는 언제일까요?",
    choices: ["1895년", "1900년", "1905년", "1915년"],
    answerIndex: 2,
    explanation: "아인슈타인은 1905년 특수상대성이론을 발표했어요. (일반상대성이론은 1915년이에요.)",
  },

  // ===== 과학 - 최상 =====
  {
    id: 36,
    category: "과학",
    difficulty: "최상",
    question: "입자의 위치와 운동량을 동시에 정확히 알 수 없다는 양자역학의 원리는 무엇일까요?",
    choices: ["파울리 배타 원리", "불확정성 원리", "상보성 원리", "중첩 원리"],
    answerIndex: 1,
    explanation: "하이젠베르크의 불확정성 원리에 따르면 위치와 운동량을 동시에 정확히 측정할 수 없어요.",
  },
  {
    id: 37,
    category: "과학",
    difficulty: "최상",
    question: "mRNA에서 하나의 아미노산을 지정하는 3개의 염기 서열 단위는 무엇일까요?",
    choices: ["오페론", "코돈", "안티코돈", "프로모터"],
    answerIndex: 1,
    explanation: "코돈(codon)은 3개의 염기로 이루어져 하나의 아미노산을 지정해요.",
  },
  {
    id: 38,
    category: "과학",
    difficulty: "최상",
    question: "표준모형에서 강력(강한 상호작용)을 매개하는 입자는 무엇일까요?",
    choices: ["광자", "글루온", "W보손", "힉스 입자"],
    answerIndex: 1,
    explanation: "글루온은 쿼크 사이의 강력을 매개하는 입자예요.",
  },
  {
    id: 39,
    category: "과학",
    difficulty: "최상",
    question: "크렙스 회로(TCA 회로)가 일어나는 미토콘드리아 내 위치는 어디일까요?",
    choices: ["외막", "내막", "기질(matrix)", "막사이공간"],
    answerIndex: 2,
    explanation: "크렙스 회로는 미토콘드리아 기질에서 일어나요.",
  },
  {
    id: 40,
    category: "과학",
    difficulty: "최상",
    question: "전기장의 변화가 자기장을 만든다는 것을 설명하는 맥스웰 방정식은 무엇일까요?",
    choices: ["가우스 법칙", "파라데이 법칙", "앙페르-맥스웰 법칙", "연속 방정식"],
    answerIndex: 2,
    explanation: "앙페르-맥스웰 법칙은 변화하는 전기장(변위 전류)이 자기장을 만든다는 것을 설명해요.",
  },

  // ===== 일반상식 - 하 =====
  {
    id: 41,
    category: "일반상식",
    difficulty: "하",
    question: "대한민국의 수도는 어디일까요?",
    choices: ["부산", "인천", "서울", "대구"],
    answerIndex: 2,
    explanation: "서울은 대한민국의 수도예요.",
  },
  {
    id: 42,
    category: "일반상식",
    difficulty: "하",
    question: "지구에서 가장 넓은 대양은 무엇일까요?",
    choices: ["대서양", "인도양", "태평양", "북극해"],
    answerIndex: 2,
    explanation: "태평양은 지구에서 가장 넓은 대양이에요.",
  },
  {
    id: 43,
    category: "일반상식",
    difficulty: "하",
    question: "1년은 몇 개월로 이루어져 있을까요?",
    choices: ["10개월", "11개월", "12개월", "13개월"],
    answerIndex: 2,
    explanation: "1년은 12개월이에요.",
  },
  {
    id: 44,
    category: "일반상식",
    difficulty: "하",
    question: "세계에서 가장 높은 산은 무엇일까요?",
    choices: ["K2", "킬리만자로", "몽블랑", "에베레스트"],
    answerIndex: 3,
    explanation: "에베레스트는 해발 약 8,849m로 세계에서 가장 높은 산이에요.",
  },
  {
    id: 45,
    category: "일반상식",
    difficulty: "하",
    question: "대한민국의 화폐 단위는 무엇일까요?",
    choices: ["엔", "위안", "원", "달러"],
    answerIndex: 2,
    explanation: "대한민국의 화폐 단위는 '원'이에요.",
  },

  // ===== 일반상식 - 중 =====
  {
    id: 46,
    category: "일반상식",
    difficulty: "중",
    question: "국제연합(UN) 안전보장이사회 상임이사국은 총 몇 개국일까요?",
    choices: ["3개국", "5개국", "7개국", "10개국"],
    answerIndex: 1,
    explanation: "미국, 영국, 프랑스, 러시아, 중국 5개국이 상임이사국이에요.",
  },
  {
    id: 47,
    category: "일반상식",
    difficulty: "중",
    question: "세계 3대 영화제 중 프랑스에서 열리는 영화제는 무엇일까요?",
    choices: ["베를린 영화제", "베니스 영화제", "칸 영화제", "선댄스 영화제"],
    answerIndex: 2,
    explanation: "칸 영화제는 프랑스 남부 도시 칸에서 매년 열리는 영화제예요.",
  },
  {
    id: 48,
    category: "일반상식",
    difficulty: "중",
    question: "노벨상을 제정한 사람은 누구일까요?",
    choices: ["알프레드 노벨", "앤드루 카네기", "헨리 포드", "존 록펠러"],
    answerIndex: 0,
    explanation: "스웨덴의 화학자 알프레드 노벨의 유언에 따라 노벨상이 만들어졌어요.",
  },
  {
    id: 49,
    category: "일반상식",
    difficulty: "중",
    question: "유럽연합(EU)이 사용하는 공동 화폐는 무엇일까요?",
    choices: ["파운드", "유로", "프랑", "마르크"],
    answerIndex: 1,
    explanation: "유로(Euro)는 여러 EU 회원국이 함께 사용하는 공동 화폐예요.",
  },
  {
    id: 50,
    category: "일반상식",
    difficulty: "중",
    question: "세계 최초의 금속활자 인쇄본으로 알려진 고려의 책은 무엇일까요?",
    choices: ["팔만대장경", "삼국유사", "직지심체요절", "동의보감"],
    answerIndex: 2,
    explanation: "직지심체요절(직지)은 1377년 인쇄된, 현존하는 세계 최초의 금속활자본으로 알려져 있어요.",
  },

  // ===== 일반상식 - 상 =====
  {
    id: 51,
    category: "일반상식",
    difficulty: "상",
    question: "GDP(국내총생산)는 무엇을 기준으로 계산하는 지표일까요?",
    choices: ["국적", "영토(국경) 안에서의 생산", "수출량", "인구수"],
    answerIndex: 1,
    explanation: "GDP는 국적과 관계없이 한 나라의 영토 안에서 이뤄진 생산을 기준으로 계산해요.",
  },
  {
    id: 52,
    category: "일반상식",
    difficulty: "상",
    question: "세계에서 가장 오래된 것으로 널리 알려진 성문법은 무엇일까요?",
    choices: ["함무라비 법전", "로마법대전", "마그나 카르타", "십계명"],
    answerIndex: 0,
    explanation: "함무라비 법전은 기원전 1750년경 만들어진, 가장 오래된 성문법으로 널리 알려져 있어요.",
  },
  {
    id: 53,
    category: "일반상식",
    difficulty: "상",
    question: "국제형사재판소(ICC)의 본부가 있는 도시는 어디일까요?",
    choices: ["뉴욕", "제네바", "헤이그", "브뤼셀"],
    answerIndex: 2,
    explanation: "국제형사재판소는 네덜란드 헤이그에 있어요.",
  },
  {
    id: 54,
    category: "일반상식",
    difficulty: "상",
    question: "경제학에서 '보이지 않는 손'이라는 표현을 쓴 학자는 누구일까요?",
    choices: ["존 메이너드 케인스", "애덤 스미스", "카를 마르크스", "밀턴 프리드먼"],
    answerIndex: 1,
    explanation: "애덤 스미스는 시장의 자율적인 조정 기능을 '보이지 않는 손'이라고 표현했어요.",
  },
  {
    id: 55,
    category: "일반상식",
    difficulty: "상",
    question: "다음 중 세계 3대 신용평가사에 속하지 않는 곳은 어디일까요?",
    choices: ["무디스", "S&P", "피치", "블룸버그"],
    answerIndex: 3,
    explanation: "블룸버그는 금융 정보·언론 회사로, 3대 신용평가사(무디스, S&P, 피치)에 속하지 않아요.",
  },

  // ===== 일반상식 - 최상 =====
  {
    id: 56,
    category: "일반상식",
    difficulty: "최상",
    question: "조약 체결 절차 등을 규정한 '조약법에 관한 협약'이 채택된 도시의 이름을 딴 국제협약은 무엇일까요?",
    choices: ["헤이그 협약", "제네바 협약", "비엔나 협약", "파리 협약"],
    answerIndex: 2,
    explanation: "1969년 오스트리아 비엔나에서 채택된 '비엔나 조약법 협약'이 조약 체결 절차를 규정해요.",
  },
  {
    id: 57,
    category: "일반상식",
    difficulty: "최상",
    question: "경제학자 애컬로프의 '레몬시장' 이론과 관련된, 정보 비대칭 상황에서 나쁜 상품이 시장에 남는 현상은 무엇일까요?",
    choices: ["도덕적 해이", "역선택", "외부효과", "희소성"],
    answerIndex: 1,
    explanation: "역선택(adverse selection)은 정보가 부족한 쪽이 불리한 선택을 하게 되는 현상이에요.",
  },
  {
    id: 58,
    category: "일반상식",
    difficulty: "최상",
    question: "세계무역기구(WTO)의 전신이 된 국제 협정은 무엇일까요?",
    choices: ["GATT", "IMF", "OECD", "NAFTA"],
    answerIndex: 0,
    explanation: "GATT(관세와 무역에 관한 일반협정)는 1995년 WTO로 발전했어요.",
  },
  {
    id: 59,
    category: "일반상식",
    difficulty: "최상",
    question: "칸트가 강조한, 스스로 세운 도덕법칙을 스스로 따르는 상태를 뜻하는 개념은 무엇일까요?",
    choices: ["타율", "자율", "공리", "실존"],
    answerIndex: 1,
    explanation: "칸트는 도덕적 자율(autonomy)을 인간 존엄성의 핵심으로 보았어요.",
  },
  {
    id: 60,
    category: "일반상식",
    difficulty: "최상",
    question: "사회학자 뒤르켐이 제시한, 급격한 사회 변동으로 규범이 무너진 상태를 뜻하는 용어는 무엇일까요?",
    choices: ["아노미", "소외", "계층화", "사회화"],
    answerIndex: 0,
    explanation: "아노미(anomie)는 사회 규범이 흔들리며 개인이 혼란을 겪는 상태를 뜻해요.",
  },

  // ===== 의학 - 하 =====
  {
    id: 61,
    category: "의학",
    difficulty: "하",
    question: "사람의 혈액형은 흔히 ABO식으로 몇 가지로 나뉠까요?",
    choices: ["2가지", "3가지", "4가지", "5가지"],
    answerIndex: 2,
    explanation: "ABO식 혈액형은 A형, B형, AB형, O형 4가지로 나뉘어요.",
  },
  {
    id: 62,
    category: "의학",
    difficulty: "하",
    question: "사람의 심장은 몇 개의 방으로 이루어져 있을까요?",
    choices: ["2개", "3개", "4개", "6개"],
    answerIndex: 2,
    explanation: "심장은 좌심방, 좌심실, 우심방, 우심실 총 4개의 방으로 나뉘어요.",
  },
  {
    id: 63,
    category: "의학",
    difficulty: "하",
    question: "감기는 주로 무엇 때문에 생길까요?",
    choices: ["세균", "곰팡이", "기생충", "바이러스"],
    answerIndex: 3,
    explanation: "감기는 대부분 여러 종류의 바이러스가 일으켜요.",
  },
  {
    id: 64,
    category: "의학",
    difficulty: "하",
    question: "건강한 성인의 평균 체온은 대략 몇 도일까요?",
    choices: ["약 34도", "약 36.5도", "약 38.5도", "약 40도"],
    answerIndex: 1,
    explanation: "사람의 정상 체온은 개인차가 있지만 보통 36.5도 전후예요.",
  },
  {
    id: 65,
    category: "의학",
    difficulty: "하",
    question: "우리 몸에서 산소를 운반하는 혈액 속 세포는 무엇일까요?",
    choices: ["백혈구", "혈소판", "적혈구", "혈장"],
    answerIndex: 2,
    explanation: "적혈구는 헤모글로빈을 통해 온몸으로 산소를 운반해요.",
  },

  // ===== 의학 - 중 =====
  {
    id: 66,
    category: "의학",
    difficulty: "중",
    question: "혈당을 낮추는 역할을 하는 호르몬은 무엇일까요?",
    choices: ["아드레날린", "인슐린", "멜라토닌", "에스트로겐"],
    answerIndex: 1,
    explanation: "인슐린은 이자(췌장)에서 분비되어 혈당을 낮춰요.",
  },
  {
    id: 67,
    category: "의학",
    difficulty: "중",
    question: "예방접종(백신)이 몸속에 만드는 것은 무엇일까요?",
    choices: ["체력", "면역(항체)", "시력", "청력"],
    answerIndex: 1,
    explanation: "백신은 특정 병원체에 대한 면역(항체)을 미리 만들도록 도와줘요.",
  },
  {
    id: 68,
    category: "의학",
    difficulty: "중",
    question: "심장에서 나온 혈액을 온몸으로 보내는 혈관은 무엇일까요?",
    choices: ["정맥", "동맥", "모세혈관", "림프관"],
    answerIndex: 1,
    explanation: "동맥은 심장에서 나온 혈액을 몸 곳곳으로 보내는 혈관이에요.",
  },
  {
    id: 69,
    category: "의학",
    difficulty: "중",
    question: "성인의 몸에는 대략 몇 개의 뼈가 있을까요?",
    choices: ["150개", "206개", "250개", "300개"],
    answerIndex: 1,
    explanation: "성인의 몸은 보통 206개의 뼈로 이루어져 있어요.",
  },
  {
    id: 70,
    category: "의학",
    difficulty: "중",
    question: "알레르기 반응이 일어날 때 몸속에서 분비되어 증상을 일으키는 물질은 무엇일까요?",
    choices: ["히스타민", "인슐린", "도파민", "콜라겐"],
    answerIndex: 0,
    explanation: "히스타민은 알레르기 반응 시 분비되어 가려움, 부종 등의 증상을 일으켜요.",
  },

  // ===== 의학 - 상 =====
  {
    id: 71,
    category: "의학",
    difficulty: "상",
    question: "심장 박동의 전기 신호를 처음 만들어내는 부위는 어디일까요?",
    choices: ["방실결절", "굴심방결절", "퍼킨제 섬유", "심실중격"],
    answerIndex: 1,
    explanation: "굴심방결절(SA node)은 심장의 자연 박동원으로, 여기서 전기 신호가 시작돼요.",
  },
  {
    id: 72,
    category: "의학",
    difficulty: "상",
    question: "간에서 여러 약물과 독소를 해독하는 대표적인 효소계는 무엇일까요?",
    choices: ["아밀라아제", "사이토크롬 P450", "리파아제", "펩신"],
    answerIndex: 1,
    explanation: "사이토크롬 P450은 간에서 약물과 독소를 대사·해독하는 대표적인 효소 시스템이에요.",
  },
  {
    id: 73,
    category: "의학",
    difficulty: "상",
    question: "신장에서 혈액을 걸러 노폐물을 거르는 기본 단위는 무엇일까요?",
    choices: ["뉴런", "네프론", "알베올리", "림프절"],
    answerIndex: 1,
    explanation: "네프론(nephron)은 신장에서 혈액을 여과하는 최소 단위예요.",
  },
  {
    id: 74,
    category: "의학",
    difficulty: "상",
    question: "최초로 항생제 페니실린을 발견한 사람은 누구일까요?",
    choices: ["루이 파스퇴르", "알렉산더 플레밍", "로베르트 코흐", "에드워드 제너"],
    answerIndex: 1,
    explanation: "알렉산더 플레밍은 1928년 우연히 페니실린을 발견했어요.",
  },
  {
    id: 75,
    category: "의학",
    difficulty: "상",
    question: "혈액 응고 과정에서 핵심 역할을 하는 혈장 단백질은 무엇일까요?",
    choices: ["알부민", "글로불린", "피브리노겐", "헤모글로빈"],
    answerIndex: 2,
    explanation: "피브리노겐은 트롬빈에 의해 피브린으로 바뀌며 혈액 응고를 돕는 단백질이에요.",
  },

  // ===== 의학 - 최상 =====
  {
    id: 76,
    category: "의학",
    difficulty: "최상",
    question: "심전도(ECG)에서 심실의 탈분극을 나타내는 파형은 무엇일까요?",
    choices: ["P파", "QRS파", "T파", "U파"],
    answerIndex: 1,
    explanation: "QRS파는 심실이 탈분극되며 수축을 준비하는 순간을 나타내요.",
  },
  {
    id: 77,
    category: "의학",
    difficulty: "최상",
    question: "인슐린 저항성이 핵심 병리인 대표적인 대사질환은 무엇일까요?",
    choices: ["제1형 당뇨병", "제2형 당뇨병", "갑상선기능저하증", "통풍"],
    answerIndex: 1,
    explanation: "제2형 당뇨병은 세포가 인슐린에 잘 반응하지 않는 인슐린 저항성이 핵심 원인이에요.",
  },
  {
    id: 78,
    category: "의학",
    difficulty: "최상",
    question: "항체를 생성하는 면역세포는 무엇일까요?",
    choices: ["T세포", "B세포(형질세포)", "호중구", "대식세포"],
    answerIndex: 1,
    explanation: "B세포는 형질세포로 분화해 항체를 만들어 분비해요.",
  },
  {
    id: 79,
    category: "의학",
    difficulty: "최상",
    question: "신장의 사구체여과율(GFR)을 추정할 때 흔히 사용하는 혈액 지표는 무엇일까요?",
    choices: ["요산", "크레아티닌", "빌리루빈", "알부민"],
    answerIndex: 1,
    explanation: "혈중 크레아티닌 농도는 신장 기능(GFR)을 추정하는 데 흔히 사용돼요.",
  },
  {
    id: 80,
    category: "의학",
    difficulty: "최상",
    question: "자가면역질환 중 관절을 주로 침범하는 대표적인 질환은 무엇일까요?",
    choices: ["루푸스", "류마티스 관절염", "건선", "크론병"],
    answerIndex: 1,
    explanation: "류마티스 관절염은 면역체계가 관절을 공격해 염증을 일으키는 자가면역질환이에요.",
  },
];
