// 상식 퀴즈 게임 - 문제 데이터
// 카테고리 4개(한국사, 과학, 일반상식, 의학) x 10문제 = 총 40문제
// 각 문제 형태: { id, category, question, choices[4], answerIndex, explanation }
const questions = [
  // 한국사
  {
    id: 1,
    category: "한국사",
    question: "조선을 건국한 인물은 누구일까요?",
    choices: ["왕건", "이성계", "김유신", "세종대왕"],
    answerIndex: 1,
    explanation: "이성계는 1392년 고려를 무너뜨리고 조선을 세운 뒤 태조가 되었어요.",
  },
  {
    id: 2,
    category: "한국사",
    question: "세종대왕이 백성을 위해 만든 우리 고유의 문자는 무엇일까요?",
    choices: ["이두", "향찰", "훈민정음", "한자"],
    answerIndex: 2,
    explanation: "훈민정음은 1443년 세종대왕이 창제하고 1446년에 반포한 우리나라 고유 문자예요.",
  },
  {
    id: 3,
    category: "한국사",
    question: "임진왜란 때 거북선을 이끌고 일본 수군을 크게 물리친 장군은 누구일까요?",
    choices: ["권율", "강감찬", "이순신", "을지문덕"],
    answerIndex: 2,
    explanation: "이순신 장군은 한산도 대첩 등에서 거북선과 판옥선을 활용해 큰 승리를 거두었어요.",
  },
  {
    id: 4,
    category: "한국사",
    question: "고려를 세운 인물은 누구일까요?",
    choices: ["왕건", "견훤", "궁예", "이성계"],
    answerIndex: 0,
    explanation: "왕건은 918년 후삼국을 통일하는 과정에서 고려를 건국했어요.",
  },
  {
    id: 5,
    category: "한국사",
    question: "우리나라의 삼국시대를 이루었던 세 나라는 무엇일까요?",
    choices: ["고구려, 백제, 가야", "고구려, 백제, 신라", "신라, 가야, 발해", "백제, 신라, 발해"],
    answerIndex: 1,
    explanation: "삼국시대는 고구려, 백제, 신라 세 나라가 한반도에서 경쟁하던 시기예요.",
  },
  {
    id: 6,
    category: "한국사",
    question: "삼국통일을 완성한 신라의 왕은 누구일까요?",
    choices: ["진흥왕", "선덕여왕", "무열왕", "문무왕"],
    answerIndex: 3,
    explanation: "문무왕은 무열왕의 뒤를 이어 676년 당나라 세력까지 몰아내며 삼국통일을 완성했어요.",
  },
  {
    id: 7,
    category: "한국사",
    question: "대조영이 세운, 고구려를 계승한 나라는 어디일까요?",
    choices: ["백제", "발해", "가야", "탐라"],
    answerIndex: 1,
    explanation: "대조영은 698년 고구려 유민과 말갈족을 모아 발해를 건국했어요.",
  },
  {
    id: 8,
    category: "한국사",
    question: "조선의 도읍(수도)이었던 곳은 지금의 어느 도시일까요?",
    choices: ["평양", "개성", "경주", "서울(한양)"],
    answerIndex: 3,
    explanation: "조선은 한양(지금의 서울)을 도읍으로 정하고 나라를 다스렸어요.",
  },
  {
    id: 9,
    category: "한국사",
    question: "만세운동으로 잘 알려진 3·1 운동이 일어난 연도는 언제일까요?",
    choices: ["1910년", "1919년", "1926년", "1945년"],
    answerIndex: 1,
    explanation: "1919년 3월 1일, 전국적으로 일제에 저항하는 독립운동이 일어났어요.",
  },
  {
    id: 10,
    category: "한국사",
    question: "우리나라가 일제로부터 해방된 광복절은 몇 월 며칠일까요?",
    choices: ["3월 1일", "6월 25일", "8월 15일", "10월 3일"],
    answerIndex: 2,
    explanation: "1945년 8월 15일, 일제강점기가 끝나고 광복을 맞았어요.",
  },

  // 과학
  {
    id: 11,
    category: "과학",
    question: "물을 이루는 화학식은 무엇일까요?",
    choices: ["CO2", "NaCl", "O2", "H2O"],
    answerIndex: 3,
    explanation: "물 분자는 수소 2개와 산소 1개가 결합한 H2O예요.",
  },
  {
    id: 12,
    category: "과학",
    question: "태양계에서 태양과 가장 가까운 행성은 무엇일까요?",
    choices: ["금성", "수성", "지구", "화성"],
    answerIndex: 1,
    explanation: "수성은 태양계 행성 중 태양에서 가장 가까운 행성이에요.",
  },
  {
    id: 13,
    category: "과학",
    question: "사람의 심장은 몇 개의 방(칸)으로 이루어져 있을까요?",
    choices: ["2개", "3개", "4개", "6개"],
    answerIndex: 2,
    explanation: "심장은 좌심방, 좌심실, 우심방, 우심실 총 4개의 방으로 나뉘어 있어요.",
  },
  {
    id: 14,
    category: "과학",
    question: "진공 속에서 빛의 속도는 대략 초당 얼마일까요?",
    choices: ["약 3천 km", "약 3만 km", "약 30만 km", "약 300만 km"],
    answerIndex: 2,
    explanation: "빛은 진공에서 1초에 약 30만 km(정확히는 약 29만 9792km)를 이동해요.",
  },
  {
    id: 15,
    category: "과학",
    question: "식물이 빛을 이용해 스스로 양분을 만드는 과정을 무엇이라고 할까요?",
    choices: ["증발", "발효", "호흡", "광합성"],
    answerIndex: 3,
    explanation: "광합성은 식물이 빛, 물, 이산화탄소를 이용해 포도당과 산소를 만드는 과정이에요.",
  },
  {
    id: 16,
    category: "과학",
    question: "DNA의 이중나선 구조를 밝혀낸 과학자로 알려진 사람들은 누구일까요?",
    choices: ["다윈", "멘델", "왓슨과 크릭", "파스퇴르"],
    answerIndex: 2,
    explanation: "왓슨과 크릭은 1953년 DNA가 이중나선 구조를 이루고 있다는 것을 밝혔어요.",
  },
  {
    id: 17,
    category: "과학",
    question: "원소 기호 'O'가 나타내는 물질은 무엇일까요?",
    choices: ["금", "철", "오스뮴", "산소"],
    answerIndex: 3,
    explanation: "산소의 원소 기호는 O예요. 오스뮴의 기호는 Os로 서로 달라요.",
  },
  {
    id: 18,
    category: "과학",
    question: "지구 대기 중 가장 많은 비율을 차지하는 기체는 무엇일까요?",
    choices: ["산소", "질소", "이산화탄소", "수소"],
    answerIndex: 1,
    explanation: "지구 대기는 약 78%가 질소, 약 21%가 산소로 이루어져 있어요.",
  },
  {
    id: 19,
    category: "과학",
    question: "뉴턴이 정립한, 물체가 서로 끌어당기는 힘에 관한 법칙은 무엇일까요?",
    choices: ["진화론", "상대성이론", "원자설", "만유인력의 법칙"],
    answerIndex: 3,
    explanation: "뉴턴은 모든 물체 사이에 서로 끌어당기는 힘이 작용한다는 만유인력의 법칙을 정립했어요.",
  },
  {
    id: 20,
    category: "과학",
    question: "사람 몸에서 가장 넓고 큰 기관(장기)은 무엇일까요?",
    choices: ["뇌", "폐", "간", "피부"],
    answerIndex: 3,
    explanation: "피부는 몸 전체를 덮고 있는 가장 크고 넓은 기관이에요.",
  },

  // 일반상식
  {
    id: 21,
    category: "일반상식",
    question: "대한민국의 수도는 어디일까요?",
    choices: ["부산", "인천", "서울", "대구"],
    answerIndex: 2,
    explanation: "서울은 대한민국의 수도이자 최대 도시예요.",
  },
  {
    id: 22,
    category: "일반상식",
    question: "지구에서 가장 넓은 대양은 무엇일까요?",
    choices: ["대서양", "인도양", "북극해", "태평양"],
    answerIndex: 3,
    explanation: "태평양은 지구 표면의 약 3분의 1을 차지하는 가장 넓은 대양이에요.",
  },
  {
    id: 23,
    category: "일반상식",
    question: "하나의 계절(예: 여름) 올림픽은 보통 몇 년마다 열릴까요?",
    choices: ["2년", "3년", "4년", "5년"],
    answerIndex: 2,
    explanation: "올림픽은 하계, 동계 각각 4년마다 열려요.",
  },
  {
    id: 24,
    category: "일반상식",
    question: "국제연합(UN) 본부가 있는 도시는 어디일까요?",
    choices: ["런던", "파리", "제네바", "뉴욕"],
    answerIndex: 3,
    explanation: "UN 본부는 미국 뉴욕에 있어요.",
  },
  {
    id: 25,
    category: "일반상식",
    question: "세계에서 가장 높은 산은 무엇일까요?",
    choices: ["K2", "킬리만자로", "몽블랑", "에베레스트"],
    answerIndex: 3,
    explanation: "에베레스트는 해발 약 8,849m로 세계에서 가장 높은 산이에요.",
  },
  {
    id: 26,
    category: "일반상식",
    question: "피자가 처음 만들어진 것으로 알려진 나라는 어디일까요?",
    choices: ["프랑스", "스페인", "그리스", "이탈리아"],
    answerIndex: 3,
    explanation: "피자는 이탈리아, 특히 나폴리 지역에서 유래한 음식으로 알려져 있어요.",
  },
  {
    id: 27,
    category: "일반상식",
    question: "1년은 몇 개월로 이루어져 있을까요?",
    choices: ["10개월", "11개월", "12개월", "13개월"],
    answerIndex: 2,
    explanation: "1년은 12개월로 이루어져 있어요.",
  },
  {
    id: 28,
    category: "일반상식",
    question: "2023년 유엔 발표 기준으로, 세계에서 인구가 가장 많은 나라는 어디일까요?",
    choices: ["중국", "미국", "인도네시아", "인도"],
    answerIndex: 3,
    explanation: "2023년 인도의 인구가 중국을 넘어서며 세계 1위가 되었다고 유엔이 발표했어요.",
  },
  {
    id: 29,
    category: "일반상식",
    question: "커피를 만드는 원료가 되는 열매(원두)를 얻는 나무는 무엇일까요?",
    choices: ["카카오나무", "바닐라나무", "커피나무", "차나무"],
    answerIndex: 2,
    explanation: "커피는 커피나무의 열매인 커피체리 속 씨(원두)를 볶아서 만들어요.",
  },
  {
    id: 30,
    category: "일반상식",
    question: "무지개는 보통 몇 가지 색깔로 표현될까요?",
    choices: ["5가지", "6가지", "7가지", "8가지"],
    answerIndex: 2,
    explanation: "무지개는 흔히 빨주노초파남보 7가지 색으로 표현돼요.",
  },

  // 의학
  {
    id: 31,
    category: "의학",
    question: "사람의 혈액형은 흔히 ABO식으로 몇 가지로 나뉠까요?",
    choices: ["2가지", "3가지", "4가지", "5가지"],
    answerIndex: 2,
    explanation: "ABO식 혈액형은 A형, B형, AB형, O형 총 4가지로 나뉘어요.",
  },
  {
    id: 32,
    category: "의학",
    question: "혈압을 측정할 때 사용하는 의료 기구는 무엇일까요?",
    choices: ["청진기", "체온계", "혈압계", "체중계"],
    answerIndex: 2,
    explanation: "혈압계는 팔에 감아 압력을 측정해 혈압 수치를 알려주는 기구예요.",
  },
  {
    id: 33,
    category: "의학",
    question: "우리 몸에서 산소를 운반하는 역할을 하는 혈액 속 세포는 무엇일까요?",
    choices: ["백혈구", "혈소판", "혈장", "적혈구"],
    answerIndex: 3,
    explanation: "적혈구는 헤모글로빈을 통해 온몸으로 산소를 운반해요.",
  },
  {
    id: 34,
    category: "의학",
    question: "혈당 조절과 밀접하게 관련된 호르몬은 무엇일까요?",
    choices: ["아드레날린", "에스트로겐", "멜라토닌", "인슐린"],
    answerIndex: 3,
    explanation: "인슐린은 이자(췌장)에서 분비되어 혈당을 낮추는 역할을 해요.",
  },
  {
    id: 35,
    category: "의학",
    question: "감기는 주로 무엇에 의해 발생할까요?",
    choices: ["세균", "곰팡이", "기생충", "바이러스"],
    answerIndex: 3,
    explanation: "감기는 대부분 여러 종류의 바이러스가 일으켜요.",
  },
  {
    id: 36,
    category: "의학",
    question: "심장에서 나온 혈액을 온몸으로 내보내는 혈관은 무엇일까요?",
    choices: ["정맥", "모세혈관", "림프관", "동맥"],
    answerIndex: 3,
    explanation: "동맥은 심장에서 나온 혈액을 몸 곳곳으로 보내는 혈관이에요.",
  },
  {
    id: 37,
    category: "의학",
    question: "예방접종(백신)의 주된 목적은 몸속에 무엇을 만드는 것일까요?",
    choices: ["체력", "시력", "청력", "면역(항체)"],
    answerIndex: 3,
    explanation: "백신은 몸이 특정 병원체에 대한 면역(항체)을 미리 만들도록 도와줘요.",
  },
  {
    id: 38,
    category: "의학",
    question: "성인의 몸에는 대략 몇 개의 뼈가 있을까요?",
    choices: ["150개", "206개", "250개", "300개"],
    answerIndex: 1,
    explanation: "성인의 몸은 보통 206개의 뼈로 이루어져 있어요.",
  },
  {
    id: 39,
    category: "의학",
    question: "충치를 예방하기 위해 가장 기본적으로 필요한 습관은 무엇일까요?",
    choices: ["운동하기", "일찍 자기", "물 많이 마시기", "꼼꼼히 양치하기"],
    answerIndex: 3,
    explanation: "꼼꼼한 양치질은 치아에 남은 음식물과 세균막(플라크)을 없애 충치를 예방해요.",
  },
  {
    id: 40,
    category: "의학",
    question: "건강한 성인의 평균 체온은 대략 몇 도일까요?",
    choices: ["약 34도", "약 36.5도", "약 38.5도", "약 40도"],
    answerIndex: 1,
    explanation: "사람의 정상 체온은 개인차가 있지만 보통 약 36.5도 전후예요.",
  },
];
